name: todo_app
description: Pro-Organizer - A Secure, Personalized To-Do & Notes Flutter Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.2

  # Supabase for authentication and backend
  supabase_flutter: ^2.3.6
  
  # Local persistence (NoSQL database) for offline functionality
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # Integrates Hive with Flutter widgets
  
  # For getting application document directory for Hive storage
  path_provider: ^2.1.4

  # For date formatting
  intl: ^0.19.0

  # For unique IDs
  uuid: ^4.5.1

  # For local notifications and recurring reminders
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  
  # Firebase for push notifications
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  
  # For sharing notes
  share_plus: ^7.2.2
  url_launcher: ^6.2.5

  # For environment variables
  flutter_dotenv: ^5.1.0

  # For shared preferences (theme persistence)
  shared_preferences: ^2.3.2
  
  # For dependency injection
  get_it: ^7.6.7

  # For form validation
  form_field_validator: ^1.1.0
  
  # For JSON serialization
  json_annotation: ^4.8.1
  
  # For image picking
  image_picker: ^1.0.7
  
  # For Google Sign In
  google_sign_in: ^6.2.1
  
  # For Facebook Sign In (optional)
  flutter_facebook_auth: ^6.0.4
  
  # For sign in with Apple (iOS) - Temporarily disabled due to Android build issues
  # sign_in_with_apple: ^5.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # For generating Hive adapters (serializer/deserializer)
  hive_generator: ^2.0.1
  build_runner: ^2.4.12 # Tool to run code generators
  json_serializable: ^6.7.1 # For JSON serialization

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - web/favicon.png
    - web/icons/
