// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG29EgRjZ-3XQpJKtYRBGM1BHeDjRoz3Q',
    appId: '1:951387755919:web:e87fdb269115cebfd3b035',
    messagingSenderId: '951387755919',
    projectId: 'todo-app-flutter-project',
    authDomain: 'todo-app-flutter-project.firebaseapp.com',
    storageBucket: 'todo-app-flutter-project.appspot.com',
    measurementId: 'G-2SMW7RV77H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG29EgRjZ-3XQpJKtYRBGM1BHeDjRoz3Q',
    appId: '1:951387755919:android:d1fb7c3da5c330a9d3b035',
    messagingSenderId: '951387755919',
    projectId: 'todo-app-flutter-project',
    storageBucket: 'todo-app-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdQf1Ycd8iT2xUzZAkJKL8Vz9BmE0H2vU',
    appId: '1:123456789012:ios:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'todo-app-demo',
    storageBucket: 'todo-app-demo.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdQf1Ycd8iT2xUzZAkJKL8Vz9BmE0H2vU',
    appId: '1:123456789012:macos:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'todo-app-demo',
    storageBucket: 'todo-app-demo.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdQf1Ycd8iT2xUzZAkJKL8Vz9BmE0H2vU',
    appId: '1:123456789012:windows:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'todo-app-demo',
    storageBucket: 'todo-app-demo.appspot.com',
  );
}
